### ISSUE TITLE
期待作者开源

### ISSUE THREAD

**Issue by zzg-971030** [MaoXinn/Dual-AMN#2]
最近看了您的文章，模型和结果都非常effective，期待您的开源，推进实体对齐社区的蓬勃发展！

**Comment by MaoXinn** [comment]
谢谢关注~ 已经好啦

**Comment by zzg-971030** [comment]
非常感谢您的开源！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaoXinn/Dual-AMN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月6日(星期天) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaoXinn/Dual-AMN] 期待作者开源 (#2)





 
Closed #2.

**Comment by xue19890510** [comment]
您好  有pytorch版本么，我自己实现的要低10个点以上
